#!/bin/sh

PIDFILE="$HOME/.wirebot/wirebot.pid"
CONFIGFILE="$HOME/.wirebot/config"
BASHFILE="$HOME/.wirebot/wirebot.sh"

# The path to your wirebot binary
WIREBOT=$( SELF=$(dirname "$0") && bash -c "cd \"$SELF\" && pwd" )

# Begin script
PROG=$(basename $0)
CMD=$1

checkpid() {
	RUNNING=0

	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`

		if [ "x$PID" != "x" ]; then
			if kill -0 $PID 2>/dev/null ; then
				RUNNING=1
			fi
		fi
	fi
}

checkrunning() {
	checkpid

	if [ $RUNNING -eq 0 ]; then
		echo "$PROG: $CMD: wirebot is not running"
		exit 1
	fi
}

case $CMD in
	start)
		checkpid

		if [ $RUNNING -eq 1 ]; then
			echo "$PROG: $CMD: wirebot (pid $PID) already running"
			exit 1
		fi

		if screen -Sdm wirebot $WIREBOT/wirebot ; then
			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
			echo "$PROG: $CMD: wirebot started"
		else
			echo "$PROG: $CMD: wirebot could not be started"
		fi
		;;

	stop)
		checkrunning

		if screen -XS wirebot quit; then
			if [ -f "$HOME/.wirebot/watcher.pid" ];then
			  rm "$HOME/.wirebot/watcher.pid"
			fi
			if [ -f "$HOME/.wirebot/wirebot.pid" ];then
			  rm "$HOME/.wirebot/wirebot.pid"
			fi
			echo "$PROG: $CMD: wirebot stopped"
		else
			echo "$PROG: $CMD: wirebot could not be stopped"
			exit 1
		fi
		;;
	status)
		checkpid

		if [ $RUNNING -eq 1 ]; then
			echo "$PROG: $CMD: wirebot is running on pid $PID."
			join_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_join=" | sed 's/.*=//g' )
			leave_check=$( cat "$BASHFILE" | grep -v "sed" | grep "user_leave=" | sed 's/.*=//g' )
			wordfilter_check=$( cat "$BASHFILE" | grep -v "sed" | grep "wordfilter=" | sed 's/.*=//g' )
			common_reply_check=$( cat "$BASHFILE" | grep -v "sed" | grep "common_reply=" | sed 's/.*=//g' )
			admin_user_check=$( cat "$BASHFILE" | grep -v "sed" | grep "admin_user=" | sed -e 's/.*=//g' -e 's/\"//g' )
			echo ""
			echo "Settings:"
			echo ""
			echo "User join    =" "$join_check"
			echo "User leave   =" "$leave_check"
			echo "Wordfilter   =" "$wordfilter_check"
			echo "Common reply =" "$common_reply_check"
			echo "Admin user   =" "$admin_user_check"
			echo ""

		fi
		;;

	screen)
		checkrunning

		if screen -rS wirebot -p 0; then
			echo "$PROG: $CMD: Entering screen session"
		else
			echo -e "\n$PROG: $CMD: wirebot is not running"
			exit 1
		fi
		;;

	restart)
		checkpid

		if [ $RUNNING -eq 1 ]; then
			if screen -XS wirebot quit; then
				if [ -f "$HOME/.wirebot/watcher.pid" ];then
				  rm "$HOME/.wirebot/watcher.pid"
				fi
				if [ -f "$HOME/.wirebot/wirebot.pid" ];then
				  rm "$HOME/.wirebot/wirebot.pid"
				fi
				echo "$PROG: $CMD: wirebot stopped"
			else
				echo "$PROG: $CMD: wirebot could not be stopped"
				exit 1
			fi
		fi

		if screen -Sdm wirebot $WIREBOT/wirebot; then
			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
			echo "$PROG: $CMD: wirebot started"
		else
			echo "$PROG: $CMD: wirebot could not be started"
		fi
		;;

	watch)
		/bin/bash "$BASHFILE" watcher_start
		;;

	nowatch)
		/bin/bash "$BASHFILE" watcher_stop
		;;

	config)
		grep -v "^#" $CONFIGFILE | grep -v "^$" | sort
		;;
	
	join_on)
		/bin/bash "$BASHFILE" user_join_on
		;;

	join_off)
		/bin/bash "$BASHFILE" user_join_off
		;;

	leave_on)
		/bin/bash "$BASHFILE" user_leave_on
		;;

	leave_off)
		/bin/bash "$BASHFILE" user_leave_off
		;;

	wordfilter_on)
		/bin/bash "$BASHFILE" wordfilter_on
		;;

	wordfilter_off)
		/bin/bash "$BASHFILE" wordfilter_off
		;;

	common_reply_on)
		/bin/bash "$BASHFILE" common_reply_on
		;;

	common_reply__off)
		/bin/bash "$BASHFILE" common_reply_off
		;;
	*)
		cat <<EOF

Usage:  wirebotctl [COMMAND]

	COMMAND:
	start			start wirebot
	stop			stop wirebot
	restart			restart wirebot
	screen			go into screen session (detach with ctrl+a and than d)
	watch/nowatch		Switch filewatching on/off
	status			show the status
	config			show the configuration
	
	join_on			Activate greeting if user joined server
	join_off		Deactivate greeting if user joined server
	
	leave_on		Activate greeting if user leaved server
	leave_off		Deactivate greeting if user leaved server

	wordfilter_on		Activate wordfilter
	wordfilter_off		Deactivate wordfilfter
	
	common_reply_on		Activate talkativeness
	common_reply_off	Deactivate talkativeness	

By Prof. Dr. Luigi 
Original by Rafaël Warnault <dev@read-write.fr>

EOF
		;;
esac
