#!/bin/sh

PIDFILE="$HOME/.wirebot/wirebot.pid"
CONFIGFILE="$HOME/.wirebot/config"

# The path to your wirebot binary
WIREBOT=$( SELF=$(dirname "$0") && bash -c "cd \"$SELF\" && pwd" )

# Begin script
PROG=$(basename $0)
CMD=$1

checkpid() {
	RUNNING=0

	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`

		if [ "x$PID" != "x" ]; then
			if kill -0 $PID 2>/dev/null ; then
				RUNNING=1
			fi
		fi
	fi
}

checkrunning() {
	checkpid

	if [ $RUNNING -eq 0 ]; then
		echo "$PROG: $CMD: wirebot is not running"
		exit 1
	fi
}

case $CMD in
	start)
		checkpid

		if [ $RUNNING -eq 1 ]; then
			echo "$PROG: $CMD: wirebot (pid $PID) already running"
			exit 1
		fi

		if screen -Sdm wirebot $WIREBOT/wirebot ; then
			/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_init
			echo "$PROG: $CMD: wirebot started"
		else
			echo "$PROG: $CMD: wirebot could not be started"
		fi
		;;

	stop)
		checkrunning

		if screen -XS wirebot quit; then
			rm "$HOME/.wirebot/wirebot.pid"
			echo "$PROG: $CMD: wirebot stopped"
		else
			echo "$PROG: $CMD: wirebot could not be stopped"
			exit 1
		fi
		;;

	screen)
		checkrunning

		if screen -rS wirebot; then
			echo "$PROG: $CMD: Entering screen session"
		else
			echo -e "\n$PROG: $CMD: wirebot is not running"
			exit 1
		fi
		;;

	restart)
		checkpid

		if [ $RUNNING -eq 1 ]; then
			if screen -XS wirebot quit; then
				rm "$HOME/.wirebot/wirebot.pid"
				echo "$PROG: $CMD: wirebot stopped"
			else
				echo "$PROG: $CMD: wirebot could not be stopped"
				exit 1
			fi
		fi

		if screen -Sdm wirebot $WIREBOT/wirebot; then
			echo "$PROG: $CMD: wirebot started"
		else
			echo "$PROG: $CMD: wirebot could not be started"
		fi
		;;

	watch)
		/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_start
		;;

	nowatch)
		/bin/bash "$HOME/.wirebot/wirebot.sh" watcher_stop
		;;

	config)
		grep -v "^#" $CONFIGFILE | grep -v "^$" | sort
		;;

	*)
		cat <<EOF

Usage: wirebotctl [start | stop | restart | watch/nowatch | screen | status | config]

	start			start wirebot
	stop			stop wirebot
	restart			restart wirebot
	screen			go into screen session
	watch/nowatch		Switch filewatching on/off
	status			show the status
	config			show the configuration
    
By Prof. Dr. Luigi 
Original by Rafaël Warnault <dev@read-write.fr>

EOF
		;;
esac
